FROM openjdk:19-jdk-alpine3.16

WORKDIR C:\Users\shamb\Desktop\Roo\code\projects\docker_project\project1\selenium-search-testing

COPY target/Selenium-Testing-0.0.1-SNAPSHOT.jar selenium-testing-0.0.1-SNAPSHOT.jar
COPY target/Selenium-Testing-0.0.1-SNAPSHOT-tests.jar selenium-testing-0.0.1-SNAPSHOT-tests.jar
COPY target/libs libs
COPY testng.xml testng.xml

ENTRYPOINT java -cp Selenium-Testing\Selenium-Testing-0.0.1-SNAPSHOT.jar:Selenium-Testing-0.0.1-SNAPSHOT-tests.jar:libs/* -DIP=$IP -DBROWSER=$BROWSER -DHUB_HOST=$HUB_HOST org.testng.TestNG $MODULE